-- MySQL Script generated by MySQL Workbench
-- 08/12/17 20:11:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bi16-java
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bi16-java-web` ;

-- -----------------------------------------------------
-- Schema bi16-java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bi16-java-web` DEFAULT CHARACTER SET utf8 ;
USE `bi16-java-web` ;

DROP TABLE IF EXISTS `bi16-java-web`.`User` ;

CREATE TABLE IF NOT EXISTS `bi16-java-web`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(100) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi16-java`.`CreditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi16-java-web`.`CreditCard` ;

CREATE TABLE IF NOT EXISTS `bi16-java-web`.`CreditCard` (
  `CreditCard_ID` INT NOT NULL AUTO_INCREMENT,
  `Cash_amount` DECIMAL(10,2) NULL,
  `Acc_User_ID` INT NOT NULL,
  PRIMARY KEY (`CreditCard_ID`),
  INDEX `fk_CreditCard_User1_idx` (`Acc_User_ID` ASC),
  CONSTRAINT `fk_CreditCard_User1`
    FOREIGN KEY (`Acc_User_ID`)
    REFERENCES `bi16-java-web`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi16-java-web`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi16-java-web`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `bi16-java-web`.`Transaction` (
  `Transaction_ID` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(10,2) NULL,
  `FROM_CreditCard_ID` INT NOT NULL,
  `TO_CreditCard_ID` INT NOT NULL,
  PRIMARY KEY (`Transaction_ID`),
  INDEX `fk_Transaction_CreditCard_idx` (`FROM_CreditCard_ID` ASC),
  INDEX `fk_Transaction_CreditCard1_idx` (`TO_CreditCard_ID` ASC),
  CONSTRAINT `fk_Transaction_CreditCard`
    FOREIGN KEY (`FROM_CreditCard_ID`)
    REFERENCES `bi16-java-web`.`CreditCard` (`CreditCard_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_CreditCard1`
    FOREIGN KEY (`TO_CreditCard_ID`)
    REFERENCES `bi16-java-web`.`CreditCard` (`CreditCard_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO DAO_WRITER;
 DROP USER DAO_WRITER;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'DAO_WRITER' IDENTIFIED BY 'H4W#T5Equ+at';
GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE `bi16-java-web`.* TO 'DAO_WRITER'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
